extends RefCounted

func test_new_games_pin_shared_roads_and_old_saves_upgrade_explicitly(t: T) -> void:
	var state: GameState=ScenarioLoader.build(Content.db(),"s1_first_light",11)
	var colony: Colony=GameModel.capital(state)
	var hash: String=state.state_hash()
	var store: AppearanceProfileStore=AppearanceProfileStore.new(); store.bind(state,"","",true)
	var anchor: Dictionary=store.anchor_for(colony.id,colony.planet_id)
	var appearance: Dictionary=store.profile_for(colony.planet_id)
	CityRoadRecipes.sync(store,state,true)
	t.eq(CityRoadRecipes.snapshot(store,colony.id),{"version":2})
	t.eq(CityRoadRecipes.snapshot(store,"hidden"),{},"only the owned requested colony has a recipe")
	var saved: Dictionary=store.save_fields(state)
	var reader: AppearanceProfileStore=AppearanceProfileStore.new(); reader.bind(state,saved["presentation"],saved["presentation_overlay"])
	t.eq(CityRoadRecipes.snapshot(reader,colony.id),{"version":2})
	t.eq(reader.anchor_for(colony.id,colony.planet_id),anchor); t.eq(reader.profile_for(colony.planet_id),appearance)
	var old: AppearanceProfileStore=AppearanceProfileStore.new(); old.bind(state)
	var old_anchor: Dictionary=old.anchor_for(colony.id,colony.planet_id)
	var old_appearance: Dictionary=old.profile_for(colony.planet_id)
	CityRoadRecipes.sync(old,state)
	t.eq(CityRoadRecipes.snapshot(old,colony.id),{},"legacy roads stay pinned on load")
	t.ok(CityRoadRecipes.can_upgrade(old)); t.ok(CityRoadRecipes.upgrade(old,state))
	t.eq(CityRoadRecipes.snapshot(old,colony.id),{"version":2})
	t.eq(old.anchor_for(colony.id,colony.planet_id),old_anchor); t.eq(old.profile_for(colony.planet_id),old_appearance)
	t.eq(state.state_hash(),hash,"road recipes are outside gameplay")

func test_future_road_recipes_are_retained_and_do_not_get_overwritten(t: T) -> void:
	var state: GameState=ScenarioLoader.build(Content.db(),"s1_first_light",11)
	var colony: Colony=GameModel.capital(state)
	var store: AppearanceProfileStore=AppearanceProfileStore.new(); store.bind(state)
	var recipe: Dictionary={"identity":AppearanceProfileStore.identity(state),"version":99,"colonies":{colony.id:{"version":99}},"future_extension":"keep"}
	t.ok(store.set_component("road",recipe))
	var before: String=store.component_raw("road")
	CityRoadRecipes.sync(store,state,true)
	t.eq(CityRoadRecipes.snapshot(store,colony.id),{})
	t.not_ok(CityRoadRecipes.can_upgrade(store)); t.not_ok(CityRoadRecipes.upgrade(store,state))
	t.eq(store.component_raw("road"),before)
	var saved: Dictionary=store.save_fields(state)
	t.eq(PresentationEnvelope.component_raws(saved["presentation"])["road"],before)
